server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: password

spring.application.name: carlease-api
springdoc.api-docs.path: /api-docs

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.h2.console.enabled=true
# default path: h2-console
#spring.h2.console.path=/h2-ui
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto= update