server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

#  server.port=8761
#  eureka.client.register-with-eureka=false
#  eureka.client.fetchRegistry=false
#  eureka.client.server.waitTimeInMsWhenSyncEmpty=0
#  eureka.client.registerWithEureka=false
#  eureka.client.fetchRegistry=false
#  eureka.client.server.waitTimeInMsWhenSyncEmpty=0